### PR TITLE
WeHelp黃挺剛 - Stage2 Week3 Assignment Submission

### PR DESCRIPTION
**Pull request by moiv3**
黃挺剛
http://35.155.26.96:8000/
http://35.155.26.96:8000/attraction/19

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Take attention on border and padding of date input element.

**Comment by moiv3** [comment]
CSS changes have been made according to design.
Changes made in detail: date-picker box size, margin/padding details, calendar icon image & placing, font family & size.

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Comment by moiv3** [comment]
merged for week3. "develop" branch will be retained for future development. "develop-experimental-functions" branch will be deleted since it is tested

**Pull request merged**
